#!/bin/bash
set -euo pipefail

: "${NSD_LOG_FILE:=/var/log/nsd.log}"
: "${DNSSEC_ALGORITHMS:=RSASHA256 ECDSAP256SHA256}"

if ! command -v ldns-keygen >/dev/null 2>&1; then
    echo "ldns-keygen not found; install ldns-tools package."
    exit 1
fi

IFS=' ' read -r -a NSD_IPV4_ARRAY <<< "${NSD_LISTEN_IPV4}"
IFS=' ' read -r -a NSD_IPV6_ARRAY <<< "${NSD_LISTEN_IPV6}"

mkdir -p /etc/nsd /etc/nsd/nsd.conf.d /etc/nsd/zones /var/run/nsd
touch "${NSD_LOG_FILE}"

{
    echo "# Auto-generated by Mail-in-a-Box container setup."
    echo "server:"
    echo "  hide-version: yes"
    echo "  logfile: \"${NSD_LOG_FILE}\""
    echo "  identity: \"\""
    echo "  zonesdir: \"/etc/nsd/zones\""
    echo "  ip-transparent: yes"
    for ip in "${NSD_IPV4_ARRAY[@]}"; do
        [ -n "$ip" ] && echo "  ip-address: ${ip}"
    done
    for ip in "${NSD_IPV6_ARRAY[@]}"; do
        [ -n "$ip" ] && echo "  ip-address: ${ip}"
    done
    echo
    echo "include: /etc/nsd/nsd.conf.d/*.conf"
} > /etc/nsd/nsd.conf

rm -f /etc/nsd/zones.conf

cat > /etc/logrotate.d/nsd <<EOF
/var/log/nsd.log {
  weekly
  missingok
  rotate 12
  compress
  delaycompress
  notifempty
}
EOF

mkdir -p "${STORAGE_ROOT}/dns/dnssec"

FIRST=1
for algo in ${DNSSEC_ALGORITHMS}; do
    if [ ! -f "${STORAGE_ROOT}/dns/dnssec/${algo}.conf" ]; then
        if [ "${FIRST}" -eq 1 ]; then
            echo "Generating DNSSEC signing keys..."
            FIRST=0
        fi
        KSK=$(umask 077; cd "${STORAGE_ROOT}/dns/dnssec"; ldns-keygen -r /dev/urandom -a "${algo}" -k _domain_)
        ZSK=$(umask 077; cd "${STORAGE_ROOT}/dns/dnssec"; ldns-keygen -r /dev/urandom -a "${algo}" _domain_)
        cat > "${STORAGE_ROOT}/dns/dnssec/${algo}.conf" <<EOF
KSK=${KSK}
ZSK=${ZSK}
EOF
    fi
done

chown -R nsd:nsd "${STORAGE_ROOT}/dns"

# Create DNSSEC update script
SCRIPT_PATH=/usr/local/bin/mailinabox-dnssec
cat > "$SCRIPT_PATH" <<'EOF'
#!/bin/sh
cd /opt/MailInABox
./tools/dns_update
EOF
chmod +x "$SCRIPT_PATH"

# Add to dcron (daily at 5am)
CRON_TMP=$(mktemp)
grep -v 'mailinabox-dnssec' /etc/crontabs/root >"$CRON_TMP" 2>/dev/null || true
{
    cat "$CRON_TMP"
    echo "# Mail-in-a-Box DNSSEC update (daily at 5am)"
    echo "0 5 * * * $SCRIPT_PATH"
} > /etc/crontabs/root
rm -f "$CRON_TMP"

chown nsd:nsd "${NSD_LOG_FILE}"
chown -R nsd:nsd /etc/nsd /var/run/nsd

