apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailinabox.fullname" . }}-config
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
data:
  PRIMARY_HOSTNAME: {{ .Values.mailinabox.env.primaryHostname | quote }}
  STORAGE_ROOT: {{ .Values.mailinabox.env.storageRoot | quote }}
  STORAGE_USER: {{ .Values.mailinabox.env.storageUser | quote }}
  DEFAULT_MTA_STS_MODE: {{ .Values.mailinabox.env.defaultMtaStsMode | quote }}
  PHP_VER: {{ .Values.mailinabox.env.phpVer | quote }}
  MTA_STS_MODE: {{ .Values.mailinabox.env.mtaStsMode | quote }}
  IN_A_DOCKER: {{ .Values.mailinabox.env.inADocker | quote }}
  ENABLE_INTERNAL_DNS: {{ .Values.mailinabox.env.enableInternalDns | quote | lower }}
  LOCAL_RESOLVER: {{ .Values.mailinabox.env.localResolver | quote }}

