#!/bin/bash
set -euo pipefail

: "${PHP_VER:=8.2}"
: "${PRIMARY_HOSTNAME:=box.example.com}"
: "${STORAGE_ROOT:=/home/user-data}"

echo "Setting up Nginx reverse proxy..."

# Configure PHP-FPM (only if WITH_PHP is true)
# ---------------------------------------------
: "${WITH_PHP:=true}"

if [ "${WITH_PHP}" = "true" ]; then
    # Convert PHP version from 8.2 to 82 for Alpine package naming
    PHP_VER_DIR=$(echo "${PHP_VER}" | tr -d '.')

    # Tell PHP not to expose its version number in the X-Powered-By header.
    sed -i "s/^;*expose_php.*/expose_php = Off/" /etc/php${PHP_VER_DIR}/php.ini 2>/dev/null || true

    # Set PHP's default charset to UTF-8
    sed -i "s/^;*default_charset.*/default_charset = \"UTF-8\"/" /etc/php${PHP_VER_DIR}/php.ini 2>/dev/null || true

    # Configure PHP-FPM pool
    POOL_CONF="/etc/php${PHP_VER_DIR}/php-fpm.d/www.conf"
    if [ -f "$POOL_CONF" ]; then
        # Set path environment
        sed -i "s/^;*env\[PATH\].*/env[PATH] = \/usr\/local\/bin:\/usr\/bin:\/bin/" "$POOL_CONF" || \
        echo "env[PATH] = /usr/local/bin:/usr/bin:/bin" >> "$POOL_CONF"

        # Configure based on available memory
        TOTAL_KB=$(awk '/MemTotal:/ {print $2}' /proc/meminfo 2>/dev/null || echo "2097152")
        TOTAL_MB=$((TOTAL_KB / 1024))

        if [ "$TOTAL_MB" -lt 1000 ]; then
            PM_MODE="ondemand"
            PM_MAX_CHILDREN=8
            PM_START_SERVERS=2
            PM_MIN_SPARE=1
            PM_MAX_SPARE=3
        elif [ "$TOTAL_MB" -lt 2000 ]; then
            PM_MODE="ondemand"
            PM_MAX_CHILDREN=16
            PM_START_SERVERS=4
            PM_MIN_SPARE=1
            PM_MAX_SPARE=6
        elif [ "$TOTAL_MB" -lt 3000 ]; then
            PM_MODE="dynamic"
            PM_MAX_CHILDREN=60
            PM_START_SERVERS=6
            PM_MIN_SPARE=3
            PM_MAX_SPARE=9
        else
            PM_MODE="dynamic"
            PM_MAX_CHILDREN=120
            PM_START_SERVERS=12
            PM_MIN_SPARE=6
            PM_MAX_SPARE=18
        fi

        sed -i "s/^pm = .*/pm = ${PM_MODE}/" "$POOL_CONF"
        sed -i "s/^pm.max_children = .*/pm.max_children = ${PM_MAX_CHILDREN}/" "$POOL_CONF"
        sed -i "s/^pm.start_servers = .*/pm.start_servers = ${PM_START_SERVERS}/" "$POOL_CONF"
        sed -i "s/^pm.min_spare_servers = .*/pm.min_spare_servers = ${PM_MIN_SPARE}/" "$POOL_CONF"
        sed -i "s/^pm.max_spare_servers = .*/pm.max_spare_servers = ${PM_MAX_SPARE}/" "$POOL_CONF"

        # Configure PHP-FPM to listen on Unix socket for local access (nginx in same container)
        # Use Unix socket for better performance
        sed -i "s|^listen = .*|listen = /var/run/php/php${PHP_VER_DIR}-fpm.sock|" "$POOL_CONF"
        sed -i "s|^;*listen.owner = .*|listen.owner = nginx|" "$POOL_CONF"
        sed -i "s|^;*listen.group = .*|listen.group = nginx|" "$POOL_CONF"
        sed -i "s|^;*listen.mode = .*|listen.mode = 0660|" "$POOL_CONF"
    fi

    # Ensure PHP-FPM socket directory exists
    mkdir -p /var/run/php
    chown nginx:nginx /var/run/php || true
fi

# Configure Nginx
# ---------------

# Update nginx.conf with minimal base settings

# Remove the line containing 'ssl_protocols' from nginx.conf (in case it already exists)
sed -i '/^\s*ssl_protocols\s/d' /etc/nginx/nginx.conf
# All domain-specific configuration is generated by mailinabox management daemon
# Move conf.d include from root level to inside http block (so upstream directives are allowed)
# We do not support outdated insecure TLS versions (1.1, 1.0)
sed -i '/^include \/etc\/nginx\/conf\.d\/\*\.conf;$/d' /etc/nginx/nginx.conf
sed -i '/^http {/a\
    server_names_hash_bucket_size 128;\
    ssl_protocols TLSv1.2 TLSv1.3;
' /etc/nginx/nginx.conf
# Add conf.d include inside http block (after the ssl_protocols line we just added)
sed -i '/ssl_protocols TLSv1.2 TLSv1.3;/a\
    include /etc/nginx/conf.d/*.conf;
' /etc/nginx/nginx.conf

# Ensure nginx conf.d directory exists (configs will be mounted from shared volume)
mkdir -p /etc/nginx/conf.d

echo "Nginx setup complete."


echo "Preparing configuration assets..."

# Create the iOS/OS X Mobile Configuration file which is exposed via the
# nginx configuration at /mailinabox-mobileconfig.
mkdir -p /var/lib/mailinabox
chmod a+rx /var/lib/mailinabox
cat /opt/mailinabox-assets/ios-profile.xml \
	| sed "s/PRIMARY_HOSTNAME/$PRIMARY_HOSTNAME/" \
	| sed "s/UUID1/$(cat /proc/sys/kernel/random/uuid)/" \
	| sed "s/UUID2/$(cat /proc/sys/kernel/random/uuid)/" \
	| sed "s/UUID3/$(cat /proc/sys/kernel/random/uuid)/" \
	| sed "s/UUID4/$(cat /proc/sys/kernel/random/uuid)/" \
	 > /var/lib/mailinabox/mobileconfig.xml
chmod a+r /var/lib/mailinabox/mobileconfig.xml

# Create the Mozilla Auto-configuration file which is exposed via the
# nginx configuration at /.well-known/autoconfig/mail/config-v1.1.xml.
# The format of the file is documented at:
# https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat
# and https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration/FileFormat/HowTo.
cat /opt/mailinabox-assets/mozilla-autoconfig.xml \
	| sed "s/PRIMARY_HOSTNAME/$PRIMARY_HOSTNAME/" \
	 > /var/lib/mailinabox/mozilla-autoconfig.xml
chmod a+r /var/lib/mailinabox/mozilla-autoconfig.xml

# Create a generic mta-sts.txt file which is exposed via the
# nginx configuration at /.well-known/mta-sts.txt
# more documentation is available on:
# https://www.uriports.com/blog/mta-sts-explained/
# default mode is "enforce". In /etc/mailinabox.conf change
# "MTA_STS_MODE=testing" which means "Messages will be delivered
# as though there was no failure but a report will be sent if
# TLS-RPT is configured" if you are not sure you want this yet. Or "none".
PUNY_PRIMARY_HOSTNAME=$(echo "$PRIMARY_HOSTNAME" | idn2)
cat /opt/mailinabox-assets/mta-sts.txt \
        | sed "s/MODE/${MTA_STS_MODE}/" \
        | sed "s/PRIMARY_HOSTNAME/$PUNY_PRIMARY_HOSTNAME/" \
         > /var/lib/mailinabox/mta-sts.txt
chmod a+r /var/lib/mailinabox/mta-sts.txt

echo "Configuration assets prepared."
