{{- if .Values.bind.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailinabox.fullname" . }}-bind
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
    component: bind
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mailinabox.selectorLabels" . | nindent 6 }}
      component: bind
  template:
    metadata:
      labels:
        {{- include "mailinabox.selectorLabels" . | nindent 8 }}
        component: bind
    spec:
      containers:
      - name: bind
        image: "https://ghcr.io/opendops/mailinadockers-bind:{{ .Values.bind.image.tag | default .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.bind.image.pullPolicy | default .Values.global.imagePullPolicy }}
        env:
        - name: BIND_LISTEN_ADDRESSES
          value: "0.0.0.0"
        - name: BIND_ALLOW_RECURSION
          value: "any"
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        volumeMounts:
        - name: bind-state
          mountPath: /var/bind
        resources:
          {{- toYaml .Values.bind.resources | nindent 10 }}
      {{- $nodeSelector := .Values.bind.nodeSelector }}
      {{- if not $nodeSelector }}
        {{- $nodeSelector = .Values.global.nodeSelector }}
      {{- end }}
      {{- if $nodeSelector }}
      nodeSelector:
        {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      {{- $tolerations := .Values.bind.tolerations }}
      {{- if not $tolerations }}
        {{- $tolerations = .Values.global.tolerations }}
      {{- end }}
      {{- if $tolerations }}
      tolerations:
        {{- toYaml $tolerations | nindent 8 }}
      {{- end }}
      {{- $affinity := .Values.bind.affinity }}
      {{- if not $affinity }}
        {{- $affinity = .Values.global.affinity }}
      {{- end }}
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      volumes:
      - name: bind-state
        persistentVolumeClaim:
          claimName: {{ include "mailinabox.fullname" . }}-bind-state
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailinabox.fullname" . }}-bind
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
    component: bind
spec:
  type: ClusterIP
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "mailinabox.selectorLabels" . | nindent 4 }}
    component: bind
{{- end }}
