{{- if and .Values.certManager.enabled .Values.gateway.enabled .Values.gateway.tls }}
{{- $primaryHostname := .Values.mailinabox.env.primaryHostname }}
{{- range $index, $tls := .Values.gateway.tls }}
{{- $hostname := $tls.hostname | default $primaryHostname }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $tls.secretName }}
  labels:
    {{- include "mailinabox.labels" $ | nindent 4 }}
spec:
  secretName: {{ $tls.secretName }}
  issuerRef:
    name: {{ $.Values.certManager.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
  - {{ $hostname | quote }}
{{- end }}
{{- end }}
