{{- if .Values.gateway.enabled }}
{{- $primaryHostname := .Values.global.primaryHostname }}
{{- $tlsConfigs := .Values.gateway.tls }}
{{- $gatewayClass := .Values.gateway.className }}
{{- $gatewayName := include "mailinabox.fullname" . }}
{{- if eq $gatewayClass "cilium" }}
{{- $gatewayName = printf "%s-gateway-http" $gatewayName }}
{{- else }}
{{- $gatewayName = printf "%s-gateway" $gatewayName }}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mailinabox.fullname" . }}-health
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $gatewayName }}
    sectionName: health
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-statics-server
      port: 10
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mailinabox.fullname" . }}-health
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $gatewayName }}
    sectionName: health
  hostnames:
  - "*.kuprin.su"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-statics-server
      port: 80
      weight: 1
{{- end }}
