{{- if .Values.gateway.enabled }}
{{- $primaryHostname := .Values.global.primaryHostname }}
{{- $tlsConfigs := .Values.gateway.tls }}
{{- $gatewayClass := .Values.gateway.className }}
{{- $gatewayName := include "mailinabox.fullname" . }}
{{- if eq $gatewayClass "cilium" }}
{{- $gatewayName = printf "%s-gateway-http" $gatewayName }}
{{- else }}
{{- $gatewayName = printf "%s-gateway" $gatewayName }}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mailinabox.fullname" . }}-http
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $gatewayName }}
    sectionName: health
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $gatewayName }}
    sectionName: http
  {{- range $index, $tls := $tlsConfigs }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $gatewayName }}
    sectionName: https-{{ $index }}
  {{- end }}
  hostnames:
  - {{ $primaryHostname | quote }}
  {{- range $tls := $tlsConfigs }}
  {{- if and $tls.hostname (ne $tls.hostname $primaryHostname) }}
  - {{ $tls.hostname | quote }}
  {{- end }}
  {{- end }}
  rules:
  - matches:
    - path:
      type: PathPrefix
      value: /
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-statics-server
      port: 10
      weight: 1
  - matches:
    - path:
        type: PathPrefix
        value: /admin/assets/
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-statics-server
      port: {{ .Values.gateway.staticsServer.port }}
      weight: 1
  {{- end }}
  - matches:
    - path:
        type: PathPrefix
        value: /
    {{- if and .Values.gateway.staticsServer.placeholderEnabled }}
    # Serve static placeholder page
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-statics-server
      port: {{ .Values.gateway.staticsServer.port }}
      weight: 1
    {{- else }}
    # Route to mailinabox service
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-mailinabox
      port: {{ .Values.mailinabox.service.ports.http }}
      weight: 1
{{- end }}
