{{- if and .Values.gateway.enabled (eq .Values.gateway.className "nginx") }}
apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: mailer-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  {{- if or .Values.gateway.logging.enabled }}
  logging:
    {{- if .Values.gateway.logging.agentLogLevel }}
    agentLevel: {{ .Values.gateway.logging.agentLogLevel | quote }}
    {{- end }}
    {{- if .Values.gateway.logging.errorLogLevel }}
    errorLevel: {{ .Values.gateway.logging.errorLogLevel | quote }}
    {{- end }}
  {{- end }}
{{- end }}
