{{- if .Values.mailinabox.storage.size }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mailinabox.fullname" . }}-storage
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mailinabox.storage.size }}
  {{- if include "mailinabox.storageClassFromRoot" (merge .Values.mailinabox.storage .) }}
  storageClassName: {{ include "mailinabox.storageClassFromRoot" (merge .Values.mailinabox.storage .) }}
  {{- end }}
---
{{- end }}

{{- if .Values.nsd.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mailinabox.fullname" . }}-nsd-conf
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nsd.storage.size }}
  {{- if include "mailinabox.storageClassFromRoot" (merge .Values.nsd.storage .) }}
  storageClassName: {{ include "mailinabox.storageClassFromRoot" (merge .Values.nsd.storage .) }}
  {{- end }}
---
{{- end }}

{{- if .Values.bind.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mailinabox.fullname" . }}-bind-state
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bind.storage.size }}
  {{- if include "mailinabox.storageClassFromRoot" (merge .Values.bind.storage .) }}
  storageClassName: {{ include "mailinabox.storageClassFromRoot" (merge .Values.bind.storage .) }}
  {{- end }}
---
{{- end }}
