{{- if and .Values.mailinabox.systemUserName .Values.mailinabox.systemUserPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailinabox.fullname" . }}-system-user
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
type: Opaque
data:
  USER_NAME: {{ .Values.mailinabox.systemUserName | b64enc }}
  USER_PASSWORD: {{ .Values.mailinabox.systemUserPassword | b64enc }}
{{- end }}
