{{- if .Values.gateway.enabled }}
{{- $primaryHostname := .Values.mailinabox.env.primaryHostname }}
{{- $tlsConfigs := .Values.gateway.tls }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "mailinabox.fullname" . }}-smtp
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "mailinabox.fullname" . }}-gateway
    sectionName: smtp
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-mailinabox
      port: 25
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "mailinabox.fullname" . }}-imap
  labels:
    {{- include "mailinabox.labels" . | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "mailinabox.fullname" . }}-gateway
    sectionName: imap
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" . }}-mailinabox
      port: 143
      weight: 1
{{- range $index, $tls := $tlsConfigs }}
{{- $hostname := $tls.hostname | default $primaryHostname }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "mailinabox.fullname" $ }}-imaps-{{ $index }}
  labels:
    {{- include "mailinabox.labels" $ | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "mailinabox.fullname" $ }}-gateway
    sectionName: imaps-{{ $index }}
  hostnames:
  - {{ $hostname | quote }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" $ }}-mailinabox
      port: 993
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "mailinabox.fullname" $ }}-smtps-{{ $index }}
  labels:
    {{- include "mailinabox.labels" $ | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "mailinabox.fullname" $ }}-gateway
    sectionName: smtps-{{ $index }}
  hostnames:
  - {{ $hostname | quote }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" $ }}-mailinabox
      port: 465
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "mailinabox.fullname" $ }}-submission-{{ $index }}
  labels:
    {{- include "mailinabox.labels" $ | nindent 4 }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "mailinabox.fullname" $ }}-gateway
    sectionName: submission-{{ $index }}
  hostnames:
  - {{ $hostname | quote }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "mailinabox.fullname" $ }}-mailinabox
      port: 587
      weight: 1
{{- end }}
{{- end }}
