global:
  primaryHostname: mailer.kuprin.su
  # gateIp: "95.179.138.227"
  storageClass: vultr-block-storage-hdd
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/system-workloads: ""
  tolerations:
    - key: node-role
      operator: Equal
      value: system-workloads
      effect: NoExecute

mailinabox:
  systemUserName: "admin"
  systemUserPassword:
    "AdminPassword123!@"
    #Set a strong password for the system user
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/log-workloads: ""
  tolerations:
    - key: node-role
      operator: "Equal"
      value: log-workloads #Change to dex-app-workloads
      effect: NoExecute
  storage:
    size: 50Gi

bind:
  # It is disabled by default
  storage:
    size: 40Gi

nsd:
  storage:
    size: 40Gi

  service:
    type: NodePort
    nodePort:
      udp: 32767
      tcp: 32767

gateway:
  enabled: true
  className: "nginx"

  # The way to select existing hardware the LoadBalancer for the gateway
  # loadBalancer:
  #   annotations:
  #     # Try to reuse constant shared LoadBalancer ID for all mail-in-a-pods gateways
  #     service.beta.kubernetes.io/vultr-loadbalancer-id: 2cafb6b6-81fa-4e18-9789-9e51799fb912

  # The way to select existing hardware the LoadBalancer for the gateway
  # infrastructure:
  #   annotations:
  #     # Try to reuse constant shared LoadBalancer ID for all mail-in-a-pods gateways
  #     service.beta.kubernetes.io/vultr-loadbalancer-id: f70816e9-6c0b-46bc-8762-060f09ddd105

  # logging:
  #   enabled: true # Enable access and error logging
  #   agentLogLevel: "debug" # Access log level: "debug", "info", "error", "panic", "fatal"
  #   errorLogLevel: "debug" # Error log level: "debug", "info", "error", "panic", "fatal"
  staticsServer:
    placeholderEnabled: false
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/log-workloads: ""
    tolerations:
      - key: node-role
        operator: "Equal"
        value: log-workloads #Change to dex-app-workloads
        effect: NoExecute

certManager:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory # Use for staging
    email: "admin@opendops.tech"
    http01:
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/system-workloads: ""
      tolerations:
        - key: node-role
          operator: Equal
          value: system-workloads
          effect: NoExecute
