apiVersion: v2
name: mailinabox
description: A Helm chart for Mail-in-a-Box on Kubernetes
type: application
version: 0.1.0
appVersion: "v73"
keywords:
  - mail
  - email
  - mailinabox
home: https://github.com/mail-in-a-box/mailinabox
maintainers:
  - name: MailInABox Team

